### ISSUE TITLE
Is `--demangler` broken?

### ISSUE THREAD

**Issue by mqtthiqs** [OfekShilon/optview2#26]
Thank you for this very useful tool.

On my machine (Apple LLVM version 15.0.0), `c++filt` does not support `-p`, so by default running `opt-viewer.py` gives me an error. 

```
c++filt: error: unknown argument '-p'
```

But if I pass option `--demangler "c++filt -n"` I get the same error as without it, so the argument does not seem to be taken into account. Am I doing something wrong?

**Comment by OfekShilon** [comment]
@mqtthiqs  Thanks for reporting this! I don't have a Mac to test on, but hopefully the fix I just pushed handles this. Can you please pull and retry?

**Comment by mqtthiqs** [comment]
That was quick, thanks!

Unfortunately I don't think it does, I still get the same error after pulling:

```
$ optview2/opt-viewer.py --split-top-folders --demangler 'c++filt -n' --source-dir ../../ .
2023-12-16 18:19:30,769 INFO Processing subfolder CMakeFiles
2023-12-16 18:19:30,769 INFO Reading YAML files...
	10 of 15/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++filt: error: unknown argument '-p'
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++filt: error: unknown argument '-p'
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++filt: error: unknown argument '-p'
	12 of 15/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++filt: error: unknown argument '-p'
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++filt: error: unknown argument '-p'
	13 of 15/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++filt: error: unknown argument '-p'
	14 of 15/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++filt: error: unknown argument '-p'
	15 of 15/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++filt: error: unknown argument '-p'
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
           ^^^^^^^^^^^^^^^^
  File "/Users/mpuech/Code/optview2/optpmap.py", line 24, in _wrapped_func
    return func(argument, exclude_names, exclude_text, collect_opt_success, annotate_external)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mpuech/Code/optview2/optrecord.py", line 331, in get_remarks
    if exclude_text_e and exclude_text_e.search(remark.message):
                                                ^^^^^^^^^^^^^^
  File "/Users/mpuech/Code/optview2/optrecord.py", line 240, in message
    values = [self.getArgString(mapping) for mapping in self.Args]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mpuech/Code/optview2/optrecord.py", line 240, in <listcomp>
    values = [self.getArgString(mapping) for mapping in self.Args]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mpuech/Code/optview2/optrecord.py", line 190, in getArgString
    value = html.escape(self.demangle(value))
                        ^^^^^^^^^^^^^^^^^^^^
  File "/Users/mpuech/Code/optview2/optrecord.py", line 100, in demangle
    cls.demangler_proc.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/mpuech/Code/optview2/opt-viewer.py", line 506, in <module>
    main()
  File "/Users/mpuech/Code/optview2/opt-viewer.py", line 464, in main
    optrecord.gather_results(filenames=files, num_jobs=args.jobs,
  File "/Users/mpuech/Code/optview2/optrecord.py", line 351, in gather_results
    remarks = optpmap.pmap(
              ^^^^^^^^^^^^^
  File "/Users/mpuech/Code/optview2/optpmap.py", line 48, in pmap
    result = pool.map(_wrapped_func, func_and_args, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/pool.py", line 774, in get
    raise self._value
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by mqtthiqs** [comment]
... and trying out another `c++filt` executable (there are two on my system) still picks the one on the path, and adds the `-p` option:

```
~/Code/optview2/opt-viewer.py --split-top-folders --demangler '/opt/homebrew/opt/llvm/bin/llvm-cxxfilt -n' --source-dir ../../ .
2023-12-16 18:24:30,860 INFO Processing subfolder CMakeFiles
2023-12-16 18:24:30,860 INFO Reading YAML files...
	10 of 15/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++filt: error: unknown argument '-p'
[...]
```

**Comment by OfekShilon** [comment]
@mqtthiqs  Can you please do this in the optview2 folder -
```
$ git pull
$ git checkout demangler_test
``` 
and then run again? This is just with some extra logging, there must be some mac phenomena I'm missing.

**Comment by mqtthiqs** [comment]
Here is the output, from `demangler_test`:

```
$ opt-viewer.py --split-top-folders --source-dir . build/Profile --demangler 'c++filt -n'
2023-12-16 22:46:41,019 INFO using received demangler arg c++filt -n
2023-12-16 22:46:41,021 INFO Processing subfolder CMakeFiles
2023-12-16 22:46:41,021 INFO Reading YAML files...
	7 of 15demangler_proc null! Using default demanglerdemangler_proc null! Using default demanglerdemangler_proc null9 of 15/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++filt: error: unknown argument '-p'
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++filt: error: unknown argument '-p'
demangler_proc null! Using default demangler/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++filt: error: unknown argument '-p'
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++filt: error: unknown argument '-p'
	12 of 15/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++filt: error: unknown argument '-p'
	13 of 15demangler_proc null! Using default demangler/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++filt: error: unknown argument '-p'
	15 of 15demangler_proc null! Using default demangler/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++filt: error: unknown argument '-p'
demangler_proc null! Using default demangler/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++filt: error: unknown argument '-p'
demangler_proc null! Using default demangler/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++filt: error: unknown argument '-p'
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
           ^^^^^^^^^^^^^^^^
  File "/Users/mpuech/Code/optview2/optpmap.py", line 25, in _wrapped_func
    return func(*args)
           ^^^^^^^^^^^
  File "/Users/mpuech/Code/optview2/optrecord.py", line 334, in get_remarks
    if exclude_text_e and exclude_text_e.search(remark.message):
                                                ^^^^^^^^^^^^^^
  File "/Users/mpuech/Code/optview2/optrecord.py", line 243, in message
    values = [self.getArgString(mapping) for mapping in self.Args]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mpuech/Code/optview2/optrecord.py", line 243, in <listcomp>
    values = [self.getArgString(mapping) for mapping in self.Args]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mpuech/Code/optview2/optrecord.py", line 193, in getArgString
    value = html.escape(self.demangle(value))
                        ^^^^^^^^^^^^^^^^^^^^
  File "/Users/mpuech/Code/optview2/optrecord.py", line 103, in demangle
    cls.demangler_proc.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/mpuech/Code/optview2/opt-viewer.py", line 506, in <module>
    main()
  File "/Users/mpuech/Code/optview2/opt-viewer.py", line 464, in main
    optrecord.gather_results(filenames=files, num_jobs=args.jobs,
  File "/Users/mpuech/Code/optview2/optrecord.py", line 354, in gather_results
    remarks = optpmap.pmap(
              ^^^^^^^^^^^^^
  File "/Users/mpuech/Code/optview2/optpmap.py", line 49, in pmap
    result = pool.map(_wrapped_func, func_and_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/pool.py", line 774, in get
    raise self._value
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by OfekShilon** [comment]
@mqtthiqs  I pushed an attempted macOS-specific workaround to the main branch. Can you please `git pull`, `git checkout main`, try again and say if this helps?

**Comment by mqtthiqs** [comment]
It works this time! Really happy to finally integrate this in our toolchain. Thanks a lot @OfekShilon for your help!

**Comment by OfekShilon** [comment]
@mqtthiqs glad to hear. Please share whether you get actionable feedback from optview2.
